<h1>Numpy</h1>

In [2]:
!pip install numpy
import numpy as np

  Obtaining dependency information for numpy from https://files.pythonhosted.org/packages/35/21/9e150d654da358beb29fe216f339dc17f2b2ac13fff2a89669401a910550/numpy-1.26.0-cp311-cp311-macosx_11_0_arm64.whl.metadata
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 99.7/99.7 kB 3.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 14.0/14.0 MB 3.3 MB/s eta 0:00:0000:0100:01


In [63]:
cnt = 0 
L = dir(np)
L.sort()
for order in L:#dir(np):
    if cnt ==12:
        cnt %=12
        print(order, end= " ")
        print()
    else:
        print(order, end= " ")
        cnt+=1

print(np.inf)

ALLOW_THREADS BUFSIZE CLIP DataSource ERR_CALL ERR_DEFAULT ERR_IGNORE ERR_LOG ERR_PRINT ERR_RAISE ERR_WARN FLOATING_POINT_SUPPORT FPE_DIVIDEBYZERO 
FPE_INVALID FPE_OVERFLOW FPE_UNDERFLOW False_ Inf Infinity MAXDIMS MAY_SHARE_BOUNDS MAY_SHARE_EXACT NAN NINF NZERO NaN 
PINF PZERO RAISE RankWarning SHIFT_DIVIDEBYZERO SHIFT_INVALID SHIFT_OVERFLOW SHIFT_UNDERFLOW ScalarType True_ UFUNC_BUFSIZE_DEFAULT UFUNC_PYVALS_NAME WRAP 
_CopyMode _NoValue _UFUNC_API __NUMPY_SETUP__ __all__ __builtins__ __cached__ __config__ __deprecated_attrs__ __dir__ __doc__ __expired_functions__ __file__ 
__former_attrs__ __future_scalars__ __getattr__ __loader__ __name__ __package__ __path__ __spec__ __version__ _add_newdoc_ufunc _builtins _distributor_init _financial_names 
_get_promotion_state _globals _int_extended_msg _mat _no_nep50_warning _pyinstaller_hooks_dir _pytesttester _set_promotion_state _specific_msg _typing _using_numpy2_behavior _utils abs 
absolute add add_docstring add_newdoc add_newdoc_ufunc all

In [67]:
print(np.inf-np.inf)

nan


<h2> NAN </h2>


In [17]:
np.NAN

nan

<h2> Shape </h2>

In [15]:
A = np.array([[1,2,3], [3,4,5]])
A.shape # (rows, columns)

(2, 3)

<h2> zeros_like </h2> 

In [16]:
A = np.array([[1,2,3], [3,4,5]])
B = np.zeros_like(A)
B

array([[0, 0, 0],
       [0, 0, 0]])

<h2> reshape & zeros </h2>

In [52]:
np.zeros(10).reshape(2,5)

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

<h2> Transpose of A </h2>

In [14]:
A.T

array([[1, 3],
       [2, 4],
       [3, 5]])

<h2> eyes </h2>

In [10]:
C = np.eye(3)
C

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

<h2> concatenate </h2>
<h3> := joining </h3>


In [53]:
# first join
print("A.T")
print(A.T)
print()
D = np.concatenate([A.T, C], axis=1)


print()
print(D)
print()

# second join

e = np.array([1,2,3]).T

# E = np.concatenate([D,  e], axis=1)
# print(D)
# print(np.array([1,2,3]))

print()
print()
e = np.array([ [3,1,5]]).T
E = np.concatenate([D,e],axis=1)
print(E)



A.T
[[1 3]
 [2 4]
 [3 5]]


[[1. 3. 1. 0. 0.]
 [2. 4. 0. 1. 0.]
 [3. 5. 0. 0. 1.]]



[[1. 3. 1. 0. 0. 3.]
 [2. 4. 0. 1. 0. 1.]
 [3. 5. 0. 0. 1. 5.]]


<h2> vstack </h2>

<h2> correlate </h2>

<h2> argmax </h2>


<h1> Pandas</h1>

In [1]:
!pip install pandas

In [2]:
import pandas as pd

In [3]:
dir(pd)

['ArrowDtype',
 'BooleanDtype',
 'Categorical',
 'CategoricalDtype',
 'CategoricalIndex',
 'DataFrame',
 'DateOffset',
 'DatetimeIndex',
 'DatetimeTZDtype',
 'ExcelFile',
 'ExcelWriter',
 'Flags',
 'Float32Dtype',
 'Float64Dtype',
 'Grouper',
 'HDFStore',
 'Index',
 'IndexSlice',
 'Int16Dtype',
 'Int32Dtype',
 'Int64Dtype',
 'Int8Dtype',
 'Interval',
 'IntervalDtype',
 'IntervalIndex',
 'MultiIndex',
 'NA',
 'NaT',
 'NamedAgg',
 'Period',
 'PeriodDtype',
 'PeriodIndex',
 'RangeIndex',
 'Series',
 'SparseDtype',
 'StringDtype',
 'Timedelta',
 'TimedeltaIndex',
 'Timestamp',
 'UInt16Dtype',
 'UInt32Dtype',
 'UInt64Dtype',
 'UInt8Dtype',
 '__all__',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__docformat__',
 '__file__',
 '__git_version__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_built_with_meson',
 '_config',
 '_is_numpy_dev',
 '_libs',
 '_pandas_datetime_CAPI',
 '_pandas_parser_CAPI',
 '_testing',
 '_typing',
 '_version_meson',
 'annota